spring:
  datasource:
    url: jdbc:mysql://localhost:3306/p2p?characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    druid:
      initial-size: 1 #初始化连接数
      min-idle: 1  #最小空闲连接
      max-active: 1 #最大活动连接
      test-on-borrow: true #获取连接时测试是否可用
      stat-view-servlet.allow: true
  jpa:
    show-sql: true #监控页面启动
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #命名策略：不使用默认的驼峰命名
  application:
    name: p2p-account-service
server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
mybatis:
  type-aliases-package: com.jizheping.api.entity
  mapper-locations: classpath:mapper/*Mapper.xml
